src/objects/Medication__c.object
<CustomObject>
    <fields>
        <fullName>Dose__c</fullName>
        <label>Dose</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Medication</label>
    <nameField>
        <label>Medication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Patient__c.object
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PatientMedication__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Medication__c</fullName>
        <label>Medication</label>
        <referenceTo>Medication__c</referenceTo>
        <relationshipLabel>Patient Medications</relationshipLabel>
        <relationshipName>PatientMedications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Patient Medications</relationshipLabel>
        <relationshipName>PatientMedications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Patient Medication</label>
    <nameField>
        <displayFormat>PM-{00000}</displayFormat>
        <label>PatientMedication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Medications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PatientMedicationSelector.cls
public with sharing class PatientMedicationSelector {

    public List<PatientMedication__c> selectByPatientId(String patientId) {
        return [
                SELECT
                        Id,
                        Medication__r.Name,
                        Medication__r.Dose__c,
                        StartDate__c,
                        EndDate__c
                FROM PatientMedication__c
                WHERE Patient__c = :patientId
        ];
    }
}