src/objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>Temperature__c</fullName>
        <label>Temperature</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pulse__c</fullName>
        <label>Pulse</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PatientService.cls
public with sharing class PatientService {

    public void updatePatientData(Patient__c patient, Map<String, Object> values) {
        String temperature = (String) values.get('Temperature__c');
        String pulse = (String) values.get('Pulse__c');
        if (String.isNotBlank(temperature)) {
            patient.Temperature__c = Decimal.valueOf(temperature);
        }
        if (String.isNotBlank(pulse)) {
            patient.Pulse__c = Decimal.valueOf(pulse);
        }
        update patient;
    }
}