src/objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temperature__c</fullName>
        <label>Temperature</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pulse__c</fullName>
        <label>Pulse</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PatientSelector.cls
public with sharing class PatientSelector {

    public List<Patient__c> selectAll() {
        return [
                SELECT
                        Age__c,
                        FirstName__c,
                        Id,
                        LastName__c,
                        Town__c,
                        Temperature__c,
                        Pulse__c
                FROM Patient__c
        ];
    }

    public List<Patient__c> selectById(String id) {
        return [
                SELECT
                        Age__c,
                        FirstName__c,
                        Id,
                        LastName__c,
                        Town__c,
                        Temperature__c,
                        Pulse__c
                FROM Patient__c
                WHERE Id = :id
                LIMIT 1
        ];
    }
}